/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2fXQNBaERNR
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-gray-800 text-white p-4">
        <h1 className="text-lg font-semibold">AI Assistant</h1>
      </header>
      <main className="flex-1 overflow-auto p-4 bg-gray-100 dark:bg-gray-800">
        <div className="flex flex-col space-y-4">
          <div className="flex items-end">
            <div className="ml-4 p-3 rounded-lg bg-gray-200 dark:bg-gray-700 max-w-md">
              <p className="text-sm">Hello! How can I assist you today?</p>
            </div>
          </div>
          <div className="flex items-end justify-end">
            <div className="mr-4 p-3 rounded-lg bg-blue-500 text-white max-w-md">
              <p className="text-sm">What's the weather like today?</p>
            </div>
          </div>
          <div className="flex items-end">
            <div className="ml-4 p-3 rounded-lg bg-gray-200 dark:bg-gray-700 max-w-md">
              <p className="text-sm">The weather today is sunny with a high of 75 degrees.</p>
            </div>
          </div>
        </div>
      </main>
      <footer className="p-4 bg-gray-200 dark:bg-gray-800">
        <div className="flex items-center space-x-2">
          <Input className="flex-1" placeholder="Type your message..." />
          <Button>Send</Button>
        </div>
      </footer>
    </div>
  )
}
